name: app_name
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+10

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  iconify_flutter: ^0.0.5
  fluttertoast: ^8.2.1

  # SECURITY
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0

  # STATE MANAGEMENT
  provider: ^6.0.5

  # UTILS
  cropperx: ^1.1.1
  file_picker: ^5.2.6
  image_picker: ^0.8.7+1
  flutter_svg: ^1.1.5
  flutter_exit_app: ^1.1.2

  # NETWORKING
  http: ^0.13.5

  # DATABASE
  hive_flutter: ^1.1.0

  # LOCALIZATION
  easy_localization: ^3.0.1

  # Audio
  audioplayers: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

  build_runner: ^2.3.3
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.1

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/app/app_logo/app_logo.png"

# flutter_native_splash:
#   color: "#fbfbfb"
#   color_dark: "#1d1d1d"
#   image: "assets/images/app/splash/light_logo.png"
#   image_dark: "assets/images/app/splash/dark_logo.png"
#   android: true
#   android_gravity: center
#   ios_content_mode: center
#   ios: true
#   web: false
#   android_12:
#     image: "assets/images/app/splash/light_logo.png"
#     icon_background_color: "#fbfbfb"
#     image_dark: "assets/images/app/splash/dark_logo.png"
#     icon_background_color_dark: "#1d1d1d"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lang/
    # - assets/images/app/logo/
    # - assets/images/app/app_logo/
    # - assets/images/app/splash/

  fonts:
    - family: Baloo Da 2
      fonts:
        - asset: assets/fonts/BalooDa2/BalooDa2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooDa2/BalooDa2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BalooDa2/BalooDa2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooDa2/BalooDa2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooDa2/BalooDa2-SemiBold.ttf
          weight: 600
